/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unesp.rc.classificaclientes.gui;

import br.unesp.rc.classificaclientes.model.ClassificacaoCliente;
import br.unesp.rc.classificaclientes.model.ClienteCidade;
import br.unesp.rc.classificaclientes.model.Contato;
import br.unesp.rc.classificaclientes.model.Pessoa;
import br.unesp.rc.classificaclientes.service.ClienteCidadeService;
import br.unesp.rc.classificaclientes.service.ContatoService;
import br.unesp.rc.classificaclientes.service.PessoaService;
import br.unesp.rc.classificaclientes.service.ServiceFactory;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author PICHAU
 */
public class ListaClientes extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form ListaClientes
     */
    public ListaClientes() {
        initComponents();
        //this.consulta = new ConsultaCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ClienteCidadeService entity = ServiceFactory.getClienteCidadeService();
        ContatoService entity2 = ServiceFactory.getContatoService();

        PessoaService entity4 = ServiceFactory.getPessoaService();
        List<ClienteCidade> clienteCidade = entity.recuperaClientes();

        ClienteCidade clienteTemp;
        Pessoa pessoa;
        ClassificacaoCliente classificacao;
        Contato contato;

        String[][] dados = new  String[clienteCidade.size()][8];

        for(int i = 0; i < clienteCidade.size(); i++){

            clienteTemp = clienteCidade.get(i);
            clienteTemp.getIdPessoa();
            pessoa = entity4.recuperaPessoa(clienteTemp.getIdPessoa());
            classificacao = entity.recuperaClassificacao(clienteTemp.getIdClassificacaoCliente());
            contato = entity2.recuperaContato(pessoa.getIdContato());

            dados[i][0] = pessoa.getNome();
            dados[i][1] = pessoa.getCpf();
            dados[i][2] = clienteTemp.getNome();
            dados[i][3] = classificacao.getStatus();
            dados[i][4] = " "+ classificacao.getPontuacao();
            dados[i][5] =     contato.getCelular() + " / " +
            contato.getTelCom() + " / " +
            contato.getTelRes();
            dados[i][6] = contato.getEmail();

        }
        tabelaClientes = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Clientes");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("CONSULTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            dados,
            new String [] {
                "Nome", "CPF", "Farmacia", "Status", "Pontuação", "Telefones", "E-mail"
            }
        ));
        jScrollPane2.setViewportView(tabelaClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        String data =(String) tabelaClientes.getModel().getValueAt(tabelaClientes.getSelectedRow(), 3);

       
        System.out.println(data);
       
        ConsultaCliente   consulta = new ConsultaCliente();
        
        consulta.nome.setText((String) tabelaClientes.getModel().getValueAt(tabelaClientes.getSelectedRow(), 0));
        consulta.cpf.setText((String) tabelaClientes.getModel().getValueAt(tabelaClientes.getSelectedRow(), 1));
        consulta.farmacia.setText((String) tabelaClientes.getModel().getValueAt(tabelaClientes.getSelectedRow(), 2));
        consulta.status.setText((String) tabelaClientes.getModel().getValueAt(tabelaClientes.getSelectedRow(), 3));
        consulta.pontuacao.setText((String) tabelaClientes.getModel().getValueAt(tabelaClientes.getSelectedRow(), 4));
        consulta.telefone.setText((String) tabelaClientes.getModel().getValueAt(tabelaClientes.getSelectedRow(), 5));
        consulta.email.setText((String) tabelaClientes.getModel().getValueAt(tabelaClientes.getSelectedRow(), 6));
        
        
        getParent().add(consulta);
        
        consulta.exibir();
        
        consulta.setVisible(true);
 

        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaClientes;
    // End of variables declaration//GEN-END:variables


}
